version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g @angular/cli
  build:
    commands:
      - ng build --prod
  post_build:
    commands:
      - echo "did it"
artifacts:
    type: zip
    base-directory: dist
    files:
      - '**/*'